### PR TITLE
Update for Inkscape 1.0

### PR DESCRIPTION
**Pull request by oskay**
Relatively small changes, I think.

* Update calls to Inkscape 1.0 extension API to avoid deprecation warnings
* Minimal cleanup of whitespace, etc.
* Handle errors from paths with curves more gracefully
* Seems to work.
* Hopefully it doesn't break anything, though I don't know what the full set of tests should be to test the features.

### CODE REVIEW

**Comment by vmario89** [comment]
Great job @oskay. Can confirm it does the job =)

grafik

**Comment by funnypolynomial** [comment]
Thanks for this @oskay! Many years ago I bought a Peggy from Evil Mad Scientist :-)
So what do I do? Start with "Merge pull request"??  My GitHub-foo is weak.

**Comment by oskay** [comment]
Yes, if you merge the pull request, this will become part of your repository.

Official docs here: https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/merging-a-pull-request

**Comment by funnypolynomial** [comment]
OK, merged. Thanks also to @vmario89 for testing (I haven't upgraded my Inkscape yet)

**Pull request merged**
